services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # Messaging
    networks:
      - sender
      - recipient

  micro-sender:
    image: "micro-sender:latest"
    build:
      context: ./micro-sender
    ports:
      - "8080:8080"
    networks:
      - sender
    environment:
      - SPRING_PROFILES_ACTIVE=sender

  micro-recipient:
    image: "micro-recipient:latest"
    build:
      context: ./micro-recipient
    ports:
      - "8082:8082"
    networks:
      - recipient
    environment:
      - SPRING_PROFILES_ACTIVE=recipient
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
    - rabbitmq
    restart: always

  micro-collector:
    image: "micro-collector:latest"
    build:
      context: ./micro-collector
    ports:
      - "8083:8083"
    networks:
      - recipient
    environment:
      - SPRING_PROFILES_ACTIVE=collector

networks:
  sender:
    driver: bridge
  recipient:
    driver: bridge
