global:
  scrape_interval: 15s  # Adjust this as needed

scrape_configs:
  - job_name: 'micro-sender'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-sender:8080']

  - job_name: 'micro-recipient'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-recipient:8082']

  - job_name: 'micro-collector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['micro-collector:8083']
